-
  name: Ping localhost
  hosts: all
  gather_facts: no
  vars:
    - name: Disable ssh verification
      value: ANSIBLE_HOST_KEY_CHECKING=False

  tasks:
    -
      name: 'Ensure python is installed'
      raw: 'apt-get install python -y'
    -
      name: Ping localhost server
      ping:
