---
- name: Creates a test and empty file on target hosts
  hosts: " {{ maquinas }}"
  become: yes
  tasks:

    - name: create /tmp dir
      file:
        path: /tmp/my_dir/
        state: absent
      
    # - name: creates a empty file on newly create dir
    #   file:
    #     path: /tmp/my_dir/new_file.txt
    #     state: touch
    #     mode: '644'

    - name: show file created
      shell: "ls -la /tmp/"
      register: ls_result

    - name: list new directory
      debug: msg=" {{ ls_result.stdout }}"  