-
  name: Delete files during tests
  hosts: linux
  tasks:
    -
      name: Delete the files that were copied during test
      file:
        path: /opt/programas/jboss/standalone.conf
        state: absent
